# Generated by Django 2.1.1 on 2018-09-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesoria',
            old_name='horaFin',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='horaInicio',
        ),
    ]
