# Generated by Django 2.1.1 on 2018-09-24 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asesorias', '0002_auto_20180916_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='facultad',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.AddField(
            model_name='seccion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesorias.Curso'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='asesoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesorias.Asesoria'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='seccion',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='asesorias.Seccion'),
        ),
    ]
