# Generated by Django 2.1.1 on 2018-09-25 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0003_auto_20180924_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
