# Generated by Django 2.1.1 on 2018-09-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('asesorias', '0004_auto_20180925_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesoriaFact', to='asesorias.Asesoria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursoFact', to='asesorias.Curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesorFact', to='accounts.User')),
                ('seccion', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='seccionFact', to='asesorias.Seccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFact', to='accounts.User')),
            ],
        ),
    ]
