# Generated by Django 2.1.1 on 2018-11-06 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0009_cita_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fechaCita',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
